export const userRegistrationDataByDay = [
    {
        day: 1,
        month: 7,
        year: 2024,
        total: 10,
        date: "1 July",
        active: 2,
        pending: 5,
    },
    {
        day: 2,
        month: 7,
        year: 2024,
        total: 15,
        date: "2 July",
        active: 2,
        pending: 5,
    },
    {
        day: 3,
        month: 7,
        year: 2024,
        total: 8,
        date: "3 July",
        active: 2,
        pending: 5,
    },
    {
        day: 4,
        month: 7,
        year: 2024,
        total: 20,
        date: "4 July",
        active: 2,
        pending: 5,
    },
    {
        day: 5,
        month: 7,
        year: 2024,
        total: 12,
        date: "5 July",
        active: 2,
        pending: 5,
    },
    {
        day: 6,
        month: 7,
        year: 2024,
        total: 4,
        date: "6 July",
        active: 2,
        pending: 5,
    },
    {
        day: 7,
        month: 7,
        year: 2024,
        total: 8,
        date: "7 July",
        active: 2,
        pending: 5,
    },
    {
        day: 8,
        month: 7,
        year: 2024,
        total: 10,
        date: "8 July",
        active: 2,
        pending: 5,
    },
    {
        day: 9,
        month: 7,
        year: 2024,
        total: 18,
        date: "9 July",
        active: 2,
        pending: 5,
    },
    {
        day: 10,
        month: 7,
        year: 2024,
        total: 11,
        date: "10 July",
        active: 2,
        pending: 5,
    },
    {
        day: 11,
        month: 7,
        year: 2024,
        total: 7,
        date: "11 July",
        active: 2,
        pending: 5,
    },
    {
        day: 12,
        month: 7,
        year: 2024,
        total: 5,
        date: "12 July",
        active: 2,
        pending: 5,
    },
    {
        day: 13,
        month: 7,
        year: 2024,
        total: 10,
        date: "13 July",
        active: 2,
        pending: 5,
    },
    {
        day: 14,
        month: 7,
        year: 2024,
        total: 10,
        date: "14 July",
        active: 2,
        pending: 5,
    },
    {
        day: 15,
        month: 7,
        year: 2024,
        total: 17,
        date: "15 July",
        active: 2,
        pending: 5,
    },
];
