export const course_data = [
    {
        id: 1,
        title: "Module 0 - Course Outline",
        duration: "10:30 minute",
        deadline: "12-02-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "60.20%",
        lessons: [
            {
                id: 1,
                title: "Introduction to course",
                duration: "10:30 minute",
                completed: true,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 2,
        title: "Module 1 - JavaScript Fundamentals",
        duration: "1:30:00",
        deadline: "12-02-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "60.20%",
        lessons: [
            {
                id: 2,
                title: "What is an Object?",
                duration: "15:00 minute",
                completed: true,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 3,
                title: "What is an Array?",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 4,
                title: "What is a String?",
                duration: "15:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 3,
        title: "Module 2 - Introduction to ES6",
        duration: "1:00:00",
        deadline: "12-02-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "60.20%",
        lessons: [
            {
                id: 5,
                title: "What is array.map()?",
                duration: "10:00 minute",
                completed: true,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 6,
                title: "What is array.filter()?",
                duration: "15:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 7,
                title: "What is array.find()?",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 4,
        title: "Module 3 - Functions and Scopes",
        duration: "2:00:00",
        deadline: "19-02-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "30.00%",
        lessons: [
            {
                id: 8,
                title: "Introduction to Functions",
                duration: "15:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 9,
                title: "Function Scopes",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 10,
                title: "Arrow Functions",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 5,
        title: "Module 4 - Asynchronous JavaScript",
        duration: "1:45:00",
        deadline: "25-02-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "20.00%",
        lessons: [
            {
                id: 11,
                title: "Understanding Callbacks",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 12,
                title: "Promises and Async/Await",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 13,
                title: "Error Handling",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 6,
        title: "Module 5 - JavaScript DOM Manipulation",
        duration: "1:20:00",
        deadline: "01-03-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "40.00%",
        lessons: [
            {
                id: 14,
                title: "Introduction to the DOM",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 15,
                title: "Selecting Elements",
                duration: "15:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 16,
                title: "Modifying the DOM",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 7,
        title: "Module 6 - JavaScript Events",
        duration: "1:30:00",
        deadline: "07-03-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "50.00%",
        lessons: [
            {
                id: 17,
                title: "Event Listeners",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 18,
                title: "Event Bubbling and Capturing",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 19,
                title: "Creating Custom Events",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 8,
        title: "Module 7 - JavaScript Object-Oriented Programming",
        duration: "2:15:00",
        deadline: "14-03-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "35.00%",
        lessons: [
            {
                id: 20,
                title: "Understanding OOP",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 21,
                title: "Prototypes and Inheritance",
                duration: "35:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 22,
                title: "Classes and Objects",
                duration: "40:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 9,
        title: "Module 8 - Advanced JavaScript Concepts",
        duration: "1:50:00",
        deadline: "21-03-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "70.00%",
        lessons: [
            {
                id: 23,
                title: "Closures",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 24,
                title: "Modules in JavaScript",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 25,
                title: "Currying and Partial Application",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 10,
        title: "Module 9 - JavaScript Testing",
        duration: "1:20:00",
        deadline: "28-03-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "45.00%",
        lessons: [
            {
                id: 26,
                title: "Introduction to Testing",
                duration: "20:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 27,
                title: "Unit Testing with Jest",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 28,
                title: "End-to-End Testing",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
    {
        id: 11,
        title: "Module 10 - JavaScript and the Web",
        duration: "2:10:00",
        deadline: "04-04-2024 11:59 PM",
        locked: false,
        completed: false,
        progress: "55.00%",
        lessons: [
            {
                id: 29,
                title: "AJAX and Fetch API",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 30,
                title: "Web Storage APIs",
                duration: "25:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
            {
                id: 31,
                title: "Service Workers",
                duration: "30:00 minute",
                completed: false,
                locked: false,
                url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
            },
        ],
    },
];
