export const course_list = [
    {
        id: 1,
        title: "Complete JavaScript Mastery",
        description: "Master JavaScript from scratch and build dynamic web applications.",
        price: 49.99,
        category: "Web Development",
        rating: 4.8,
        studentsEnrolled: 1500,
        duration: "30 hours",
        level: "Beginner to Advanced",
        imageUrl: "https://example.com/javascript-course.jpg",
        instructor: "John Doe",
    },
    {
        id: 2,
        title: "Laravel 8 - The Complete Guide",
        description: "Learn Laravel 8 from the ground up and build powerful web applications.",
        price: 59.99,
        category: "Web Development",
        rating: 4.7,
        studentsEnrolled: 1200,
        duration: "40 hours",
        level: "Intermediate to Advanced",
        imageUrl: "https://example.com/laravel-course.jpg",
        instructor: "Jane Smith",
    },
    {
        id: 3,
        title: "Python for Data Science and Machine Learning",
        description:
            "Become a data scientist by mastering Python and its libraries for data analysis and machine learning.",
        price: 69.99,
        category: "Data Science",
        rating: 4.9,
        studentsEnrolled: 1800,
        duration: "50 hours",
        level: "Beginner to Advanced",
        imageUrl: "https://example.com/python-data-science-course.jpg",
        instructor: "Emily Johnson",
    },
    {
        id: 4,
        title: "React Native - Build Mobile Apps with JavaScript",
        description: "Learn how to build cross-platform mobile applications using React Native.",
        price: 54.99,
        category: "Mobile Development",
        rating: 4.6,
        studentsEnrolled: 1100,
        duration: "35 hours",
        level: "Intermediate",
        imageUrl: "https://example.com/react-native-course.jpg",
        instructor: "Michael Brown",
    },
    {
        id: 5,
        title: "Complete WordPress Development",
        description: "Learn how to create professional websites and blogs using WordPress.",
        price: 39.99,
        category: "Web Development",
        rating: 4.5,
        studentsEnrolled: 2000,
        duration: "25 hours",
        level: "Beginner",
        imageUrl: "https://example.com/wordpress-course.jpg",
        instructor: "Sarah Davis",
    },
    {
        id: 6,
        title: "Angular - The Complete Guide",
        description: "Master Angular and build dynamic web applications with this powerful framework.",
        price: 59.99,
        category: "Web Development",
        rating: 4.7,
        studentsEnrolled: 1400,
        duration: "40 hours",
        level: "Intermediate to Advanced",
        imageUrl: "https://example.com/angular-course.jpg",
        instructor: "David Wilson",
    },
    {
        id: 7,
        title: "Complete SEO Training",
        description: "Learn SEO strategies to boost your website's visibility and ranking in search engines.",
        price: 34.99,
        category: "Marketing",
        rating: 4.6,
        studentsEnrolled: 1700,
        duration: "20 hours",
        level: "All Levels",
        imageUrl: "https://example.com/seo-course.jpg",
        instructor: "Laura Garcia",
    },
    {
        id: 8,
        title: "Node.js - The Complete Developer Guide",
        description: "Learn Node.js from scratch and build scalable server-side applications.",
        price: 59.99,
        category: "Web Development",
        rating: 4.8,
        studentsEnrolled: 1300,
        duration: "45 hours",
        level: "Intermediate to Advanced",
        imageUrl: "https://example.com/nodejs-course.jpg",
        instructor: "Daniel Martinez",
    },
    {
        id: 9,
        title: "UX/UI Design Bootcamp",
        description: "Master the fundamentals of UX/UI design and create user-friendly interfaces.",
        price: 49.99,
        category: "Design",
        rating: 4.9,
        studentsEnrolled: 1600,
        duration: "35 hours",
        level: "Beginner to Intermediate",
        imageUrl: "https://example.com/ux-ui-design-course.jpg",
        instructor: "Sophia Lee",
    },
    {
        id: 10,
        title: "Data Structures and Algorithms in Java",
        description: "Learn the fundamentals of data structures and algorithms using Java.",
        price: 64.99,
        category: "Programming",
        rating: 4.7,
        studentsEnrolled: 1500,
        duration: "40 hours",
        level: "Intermediate",
        imageUrl: "https://example.com/java-dsa-course.jpg",
        instructor: "Andrew Kim",
    },
];
