export const nttn_data = () => {
    return [
        {
            uid: 1,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 2,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: null,
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 3,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 4,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: null,
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 5,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 6,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 7,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 8,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 9,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 10,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 11,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 12,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 13,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 14,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
        {
            uid: 15,
            nttn_id: 123654,
            pop_id: "12365",
            pop_type: "radio",
            provider_name: "Summit",
            status: "active",
            created_at: "06-04-2024 03:42 PM",
        },
    ];
};
