export const package_data = [
    {
        id: 1,
        en_title: "Desh",
        bn_title: "Desh",
        title: "Desh",
        validity: "36000",
        status: "Active",
        price: "500",
        upload_speed: "5",
        download_speed: "5",
        is_active: 1,
    },
    {
        id: 2,
        en_title: "Bondhu",
        bn_title: "Bondhu",
        title: "Bondhu",
        validity: "36000",
        status: "Active",
        price: "800",
        upload_speed: "5",
        download_speed: "5",
        is_active: 1,
    },
    {
        id: 3,
        en_title: "Somoy",
        bn_title: "Somoy",
        title: "Somoy",
        validity: "36000",
        status: "Inactive",
        price: "1000",
        upload_speed: "5",
        download_speed: "5",
        is_active: 0,
    },
];
