export const wifi_statement_data = [
    {
        full_name: "Test user",
        username: "test-user",
        password: "123456",
        month: "Jun-2024",
        amount: 500,
        profit: 0,
        payment_date: "02-02-2024 10:20 AM",
        expire_date: "01-03-2024 10:20 AM",
        package_name: "Desh",
        original_agent_commission: 0,
        sub_agent_commission: 0,
        agent_commission: 0,
        owner_type: "admin",
        owner_id: 10,
        added_by: "Myself",
    },
    {
        full_name: "Test user 2",
        username: "test-user2",
        password: "123456",
        month: "Jun-2024",
        amount: 500,
        profit: 80,
        payment_date: "02-02-2024 10:20 AM",
        expire_date: "01-03-2024 10:20 AM",
        package_name: "Desh",
        original_agent_commission: 30,
        sub_agent_commission: 0,
        agent_commission: 30,
        owner_type: "agent",
        owner_id: 11,
        added_by: "Test (Agent)",
    },
    {
        full_name: "Test user 3",
        username: "test-user3",
        password: "123456",
        month: "Jun-2024",
        amount: 500,
        profit: 80,
        payment_date: "02-02-2024 10:20 AM",
        expire_date: "01-03-2024 10:20 AM",
        package_name: "Desh",
        original_agent_commission: 30,
        sub_agent_commission: 10,
        agent_commission: 20,
        owner_type: "sub_agent",
        owner_id: 12,
        added_by: "Test (Sub-Agent)",
    },
];
